apiVersion: v1
kind: Service
metadata:
  name: {{ include "arangodb.fullname" . }}
  labels:
    {{- include "arangodb.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8529
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "arangodb.selectorLabels" . | nindent 4 }}
