name: PR Validations

on:
  pull_request:
    branches:
      - 'main'

jobs:
  validate-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: services/nodejs/apps/package-lock.json

      - name: Install backend dependencies
        run: |
          cd services/nodejs/apps
          npm install

      - name: Build backend
        run: |
          cd services/nodejs/apps
          npm run build

      # - name: Run backend tests
      #   run: |
      #     cd services/nodejs/apps
      #     npm test

  validate-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      # - name: Run frontend tests
      #   run: |
      #     cd frontend
      #     npm test


  validate-python-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: services/python/pyproject.toml

      - name: Install Python dependencies
        run: |
          cd services/python
          pip install .[dev]
          pip install ruff pytest

      - name: Run Python linting
        run: |
          cd services/python
          ruff check .
  
  ruff-lint-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run ruff on changed Python files
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.py$' | if [ $(wc -l) -gt 0 ]; then xargs ruff check --select ANN201,ANN202,ANN204,ANN205,ANN206,N804; fi